Import('*')

ftl_yaftl_src = env.Localize([
	'yaftl_mem.c',
	'yaftl_common.c',
	'yaftl.c',
	'yaftl_gc.c',
	'l2v.c',
	])

ftl_yaftl = env.CreateModule('ftl-yaftl', ftl_yaftl_src)
ftl_yaftl.Append(CPPPATH = [Dir('includes')])
ftl_yaftl.Append(CPPDEFINES = ['CONFIG_FTL_YAFTL'])
