Import("*")

env = env.Clone()
env.Append(CPPPATH = [Dir('includes')])
env.Append(CPPDEFINES = ['ARM_A8', 'CONFIG_S5L8920', 'MALLOC_NO_WDT'])

env.AddModules([
	"acm",
	"nor-spi",
	"usb-synopsys",
	"vfl-vfl",
	"vfl-vsvfl",
	"ftl-yaftl",
	])

plat_s5l8920_src = arch_arm_src + base_src + env.Localize([
	's5l8920.c',
	'usbphy.c',
	'aes.c',
	'buttons.c',
	'chipid.c',
	'clock.c',
	'event.c',
	'gpio.c',
	'i2c.c',
	'interrupt.c',
	'clcd.c',
	'mipi_dsim.c',
	'miu.c',
	'mmu.c',
	'power.c',
	'spi.c',
	'timer.c',
	'cdma.c',
	'h2fmi.c',
	'uart.c',
	]) + hfs_src
Export('plat_s5l8920_src')

env.SConscript('iPhone3GS.SConscript', 'env')
