Import("*")

env = env.Clone()
env.Append(CPPPATH = [Dir('includes')])
env.Append(ASFLAGS = ['-L'+str(Dir('includes'))])
env.Append(CPPDEFINES = ['ARM_A8', 'CONFIG_S5L8920', 'MALLOC_NO_WDT'])

env.AddModules([
	"nor-spi",
	"usb-synopsys",
	])

plat_s5l8920_src = arch_arm_src + env.Localize([
	# Include the bits of base_src we use
	# until we implement it all
	'#device.c',
	'#mtd.c',
	'#bdev.c',
	'#openiboot.c',
	'#util.c',
	'#malloc.c',
	'#sha1.c',
	'#tasks.c',
	'#printf.c',
	'#framebuffer.c',
	'#acm.c',
	'#commands.c',
	'#actions.c',
	'#scripting.c',
	'#stb_image.c',
	'#images.c',
	'#syscfg.c',
	'#nvram.c',

	's5l8920.c',
	'usbphy.c',
	'aes.c',
	'buttons.c',
	'chipid.c',
	'clock.c',
	'event.c',
	'gpio.c',
	'i2c.c',
	'interrupt.c',
	'lcd.c',
	'miu.c',
	'mmu.c',
	'power.c',
	'spi.c',
	'timer.c',
	'uart.c',
	]) + hfs_src
Export('plat_s5l8920_src')

env.SConscript('iPhone3GS.SConscript', 'env')
