Import("*")

env = env.Clone()
env.Append(CPPPATH = [Dir('includes')])
env.Append(ASFLAGS = ['-L'+str(Dir('includes'))])
env.Append(CPPDEFINES = ['CONFIG_ARM'])

arch_arm_src = env.Localize([
	'entry.S',
	'asmhelpers.S',
	'arm.c',
	])
Export('arch_arm_src')

env.SConscript([
	'#plat-s5l8720/SConscript',
	'#plat-s5l8900/SConscript',
	'#plat-s5l8920/SConscript',
	'#plat-a4/SConscript',
	], 'env')
