Import("*")

env = env.Clone()
env.Append(CPPPATH = [Dir('includes')])
env.Append(ASFLAGS = ['-L'+str(Dir('includes'))])
env.Append(CPPDEFINES = ['ARM11', 'CONFIG_S5L8900'])

env.AddModules([
	"usb-synopsys",
	])

plat_s5l8900_src = arch_arm_src + base_src + env.Localize([
	's5l8900.c',
	'accel.c',
	'aes.c',
	'buttons.c',
	'chipid.c',
	'clock.c',
	'dma.c',
	'event.c',
	'gpio.c',
	'i2c.c',
	'interrupt.c',
	'lcd.c',
	'miu.c',
	'mmu.c',
	'nand.c',
	'ftl.c',
	#'nor.c',
	'pmu.c',
	'power.c',
	'sdio.c',
	'spi.c',
	'timer.c',
	'uart.c',
	'usbphy.c',
	'wdt.c',
	'wlan.c',
	]) + hfs_src
Export('plat_s5l8900_src')

env.SConscript('iPhone3G.SConscript', 'env')
env.SConscript('iPhone2G.SConscript', 'env')
env.SConscript('iPod1G.SConscript', 'env')
