#ifndef HW_CLCD_H
#define HW_CLCD_H

#define CLCD_BASE			0x85400000
#define CLCD_FRAMEBUFFER	0x4FD00000
#define CLCD_CLOCKGATE_1	0x2F
#define CLCD_CLOCKGATE_2	0x2B
#define CLCD_CLOCKGATE_3	0x1B

#define VIDCON1_IVCLKSHIFT 3
#define VIDCON1_IHSYNCSHIFT 2
#define VIDCON1_IVSYNCSHIFT 1
#define VIDCON1_IVDENSHIFT 0

#define VIDTCON_BACKPORCHSHIFT 16
#define VIDTCON_BACKPORCHMASK 0xFF
#define VIDTCON_FRONTPORCHSHIFT 8
#define VIDTCON_FRONTPORCHMASK 0xFF
#define VIDTCON_SYNCPULSEWIDTHSHIFT 0
#define VIDTCON_SYNCPULSEWIDTHMASK 0xFF
#define VIDTCON2_LINEVALMASK 0x3FF
#define VIDTCON2_LINEVALSHIFT 0
#define VIDTCON2_HOZVALMASK 0x3FF
#define VIDTCON2_HOZVALSHIFT 16

#define DISPLAYID 0

#endif
