#ifndef  __A4_HARDWARE_RADIO
#define  __A4_HARDWARE_RADIO

#define RADIO_GPIO_BB_RESET 0x1405
#define RADIO_GPIO_RADIO_ON 0x1407
#define RADIO_GPIO_RESET_DETECT 0x603
#define RADIO_UART 1
#define RADIO_HIGH_IS_ZERO

#endif //__A4_HARDWARE_RADIO
