#ifndef HW_BUTTONS_H
#define HW_BUTTONS_H

// Device
#define BUTTONS_HOME 0xC01
#define BUTTONS_HOLD 0xC02
#define BUTTONS_VOLUP 0x902
#define BUTTONS_VOLDOWN 0xC00

#define BUTTONS_HOME_IRQ 0x79
#define BUTTONS_HOLD_IRQ 0x7A
#define BUTTONS_VOLUP_IRQ 0x62
#define BUTTONS_VOLDOWN_IRQ 0x78

#define BUTTONS_IIC_STATE 0x4B

#define BUTTONS_HOLD_IRQTYPE 1
#define BUTTONS_HOME_IRQTYPE 1
#define BUTTONS_VOLUP_IRQTYPE 1
#define BUTTONS_VOLDOWN_IRQTYPE 1
#define BUTTONS_RINGERAB_IRQTYPE 1

#define BUTTONS_HOLD_IRQLEVEL 1
#define BUTTONS_HOME_IRQLEVEL 1
#define BUTTONS_VOLUP_IRQLEVEL 1
#define BUTTONS_VOLDOWN_IRQLEVEL 1
#define BUTTONS_RINGERAB_IRQLEVEL 1

#define BUTTONS_HOLD_IRQAUTOFLIP 1
#define BUTTONS_HOME_IRQAUTOFLIP 1
#define BUTTONS_VOLUP_IRQAUTOFLIP 1
#define BUTTONS_VOLDOWN_IRQAUTOFLIP 1
#define BUTTONS_RINGERAB_IRQAUTOFLIP 1

#endif

