#ifndef HW_PMU_H
#define HW_PMU_H

#define PMU_I2C_BUS 0

// Power
#define PMU_SETADDR	0xE6
#define PMU_GETADDR	0xE7

// Values
#define PMU_MAXREG	0xF

// Registers
#define PMU_OOCSHDWN 0xA
#define PMU_ADCSTS 0x2
#define PMU_ADCCON 0x40
#define PMU_ADCOUT1 0x41
#define PMU_ADCOUT2 0x42
#define PMU_GPMEM_START 0x60
#define PMU_VOLTAGE1 0x6E
#define PMU_VOLTAGE2 0x6D

#define PMU_RTCSC_MASK 0x7F
#define PMU_RTCMN_MASK 0x7F
#define PMU_RTCHR_MASK 0x3F
#define PMU_RTCWD_MASK 0x07
#define PMU_RTCDT_MASK 0x3F
#define PMU_RTCMT_MASK 0x1F
#define PMU_RTCYR_MASK 0xFF

#define PMU_OOCSHDWN_GOSTBY (1 << 0)

#define PMU_MBCS1_ADAPTPRES (1 << 2)
#define PMU_MBCS1_USBOK (1 << 0)

#define PMU_ADCC1_ADCINMUX_SHIFT 4
#define PMU_ADCC1_ADCINMUX_MASK 0xF
#define PMU_ADCC1_ADC_AV_SHIFT 2
#define PMU_ADCC1_ADCSTART 0x1
#define PMU_ADCC1_ADCRES 0x2

#define PMU_ADCC1_ADC_AV_1 0x0
#define PMU_ADCC1_ADC_AV_4 0x1
#define PMU_ADCC1_ADC_AV_8 0x2
#define PMU_ADCC1_ADC_AV_16 0x3

#define PMU_ADCC1_ADCINMUX_BATSNS_DIV 0x0
#define PMU_ADCC1_ADCINMUX_BATSNS_SUB 0x1
#define PMU_ADCC1_ADCINMUX_ADCIN2_DIV 0x2
#define PMU_ADCC1_ADCINMUX_ADCIN2_SUB 0x3
#define PMU_ADCC1_ADCINMUX_BATTEMP 0x6
#define PMU_ADCC1_ADCINMUX_ADCIN1 0x7

#endif

