Import("*")

env = env.Clone()
env.Append(CPPPATH = [Dir('includes')])
env.Append(CPPDEFINES = ['ARM_A8', 'CONFIG_A4', 'MALLOC_NO_WDT', 'BIG_FONT'])

env.AddModules([
	"acm",
	"usb-synopsys",
	"vfl-vfl",
	"vfl-vsvfl",
	"ftl-yaftl",
	])

plat_a4_src = arch_arm_src + base_src + env.Localize([
	'a4.c',
	'aes.c',
	'buttons.c',
	'chipid.c',
	'clock.c',
	'event.c',
	'gpio.c',
	'i2c.c',
	'interrupt.c',
	'mipi_dsim.c',
	'clcd.c',
	'miu.c',
	'mmu.c',
	'pmu.c',
	'power.c',
	'spi.c',
	'timer.c',
	'uart.c',
	'cdma.c',
	'usbphy.c',
	'h2fmi.c',
	'sdio.c',
	]) + hfs_src
Export('plat_a4_src')

env.SConscript('iPhone4G.SConscript', 'env')
env.SConscript('iPad1G.SConscript', 'env')
env.SConscript('aTV2G.SConscript', 'env')
env.SConscript('iPodTouch4G.SConscript', 'env')
