Import("*")

env = env.Clone()
env.Append(CPPPATH = [Dir('includes')])
env.Append(ASFLAGS = ['-L'+str(Dir('includes'))])
env.Append(CPPDEFINES = ['ARM_A8', 'CONFIG_A4', 'MALLOC_NO_WDT'])

env.AddModules([
	"usb-synopsys",
	])

plat_a4_src = arch_arm_src + env.Localize([
	# Include the bits of base_src we use
	# until we implement it all
	'#device.c',
	'#mtd.c',
	'#bdev.c',
	'#openiboot.c',
	'#util.c',
	'#malloc.c',
	'#tasks.c',
	'#printf.c',
	'#framebuffer.c',
	'#acm.c',
	'#commands.c',
	'#stb_image.c',

	'a4.c',
	'buttons.c',
	'chipid.c',
	'clock.c',
	'event.c',
	'gpio.c',
	'i2c.c',
	'interrupt.c',
	'lcd.c',
	'miu.c',
	'mmu.c',
	'power.c',
	'spi.c',
	'timer.c',
	'uart.c',
#	'cdma.c',
	'usbphy.c',
	]) + hfs_src
Export('plat_a4_src')

env.SConscript('iPhone4G.SConscript', 'env')
env.SConscript('iPad1G.SConscript', 'env')
