Import('*')

installer_src = env.Localize([
	'installer.c',
	])

installer = env.CreateModule('installer', installer_src)
installer.Append(CPPPATH = [Dir('includes'), Dir('.')])

graphics = env.Bin2CList([
	'installerLogo',
	'installerBarEmpty',
	'installerBarFull',
	], "images/%s.png", "images/%sPNG.h", "data%sPNG")
installer.Depends(graphics)

def InstallerEnv(env):
	e2 = env.Clone()
	e2.AddModules(["installer"])
	return e2
env.AddMethod(InstallerEnv, "InstallerEnv")
